import type { EffectiveRules } from "./api";

export const CANADA_RIGHTS_REVIEWED_AT = "2026-08-05T00:00:00.000Z";

type Entry = {
  status?: "verified" | "partial";
  access: string;
  accessBullets: string[];
  training: string;
  trainingBullets: string[];
  questions?: string[];
  prohibited?: string[];
  source: string;
  url: string;
  complaint: string;
  complaintUrl: string;
};

const ENTRIES: Record<string, Entry> = {
  AB: { access:"Alberta's Service Dogs Act protects qualified service-dog teams in public places. A qualified team should carry its Alberta or otherwise recognized service-dog identification.", accessBullets:["Owner-trained and privately trained dogs can qualify through Alberta's assessment process.","Non-public food-preparation, sterile and restricted areas are not included."], training:"A dog in training has the same public-access protection only with a trainer, including an owner-trainer, who is under the supervision of a qualified organization.", trainingBullets:["Without a qualified organization, training access depends on the property's voluntary permission.","Qualified organizations can issue service-dog-in-training identification."], questions:["A business may ask to see identification establishing protected status under Alberta's statutory scheme."], prohibited:["Refuse a qualified team access after protected status is established","Segregate a qualified team into a designated service-dog area"], source:"Government of Alberta — Service dogs in public", url:"https://www.alberta.ca/service-dogs-in-public", complaint:"Report a Service Dogs Act concern to Alberta's Service Dog Assessment Team.", complaintUrl:"https://www.alberta.ca/report-concern-about-service-dogs" },
  BC: { access:"British Columbia's Guide Dog and Service Dog Act protects certified teams in public places and housing. Certification is voluntary; Human Rights Code accommodation may also apply to an uncertified team.", accessBullets:["Certification may follow an accredited program or provincial public-safety assessment.","A lack of certification does not automatically end the duty to consider human-rights accommodation."], training:"The Act protects certified dog trainers while training a certified dog-in-training.", trainingBullets:["The statutory training right does not automatically cover every informal or owner-training situation.","Confirm the certificate requirements before relying on the Act."], questions:["For rights claimed under the Act, a business may ask to see the provincial certificate."], prohibited:["Deny a certified team access or charge an extra fee because of the dog","Refuse to consider accommodation merely because a team is not certified"], source:"Government of BC — Guide and service dogs", url:"https://www2.gov.bc.ca/gov/content/justice/human-rights/guide-and-service-dog", complaint:"Use the provincial service-dog program or BC Human Rights Tribunal route appropriate to the issue.", complaintUrl:"https://www2.gov.bc.ca/gov/content/justice/human-rights/guide-and-service-dog/public-rights" },
  MB: { access:"Manitoba's accessible customer-service rules require service-animal access in public-facing areas unless another law excludes the animal.", accessBullets:["The animal must be under the person's control.","If another law excludes the animal, another accessible way to receive service must be provided."], training:"No province-wide Manitoba rule has been verified that automatically gives every service animal in training the same access as a working service animal.", trainingBullets:["Seek property permission unless the animal already meets the legal service-animal definition."], questions:["If the role is not obvious, a provider may make a reasonable inquiry or request information showing disability-related training."], prohibited:["Apply a pet rule without recognizing a qualifying service animal","Fail to offer an accessible alternative when another law excludes the animal"], source:"Manitoba — Accessible Customer Service Standard Regulation", url:"https://web2.gov.mb.ca/laws/regs/current/171-2015.php", complaint:"Contact the Manitoba Human Rights Commission.", complaintUrl:"https://www.manitobahumanrights.ca/complaints/complaints.html" },
  NB: { access:"New Brunswick treats service-animal use as disability accommodation under the Human Rights Act in services, housing and employment.", accessBullets:["Accommodation is individualized to the point of undue hardship.","The protection is not limited to dogs or one government-issued card."], training:"The official guideline does not create automatic public access for every animal that is only in training.", trainingBullets:["Confirm permission unless the animal already qualifies as the person's service animal."], questions:["When need is not apparent, a provider may request limited reasonable information needed to assess accommodation."], prohibited:["Refuse service or housing without considering reasonable disability accommodation","Demand more medical information than reasonably necessary"], source:"New Brunswick Human Rights Commission — Service animals guideline", url:"https://www.gnb.ca/en/topic/family-home-community/housing-property/renters/service-animals-2017.html", complaint:"Contact the New Brunswick Human Rights Commission.", complaintUrl:"https://www2.gnb.ca/content/gnb/en/departments/nbhrc.html" },
  NL: { access:"Newfoundland and Labrador's Service Animal Act protects people using qualifying service animals in public facilities and housing and prohibits an extra animal fee.", accessBullets:["The animal must meet the regulation's training or recognition qualifications.","Its role must be readily apparent or supported by an authorized health-professional letter."], training:"The Act and regulations do not create a separate automatic public-access category for an animal merely in training.", trainingBullets:["Seek voluntary permission until the animal satisfies the statutory qualifications."], questions:["If use is not readily apparent, a provider may ask for the authorized professional letter contemplated by the Act."], prohibited:["Deny access solely because a person is accompanied by a qualifying service animal","Charge an extra service-animal admission or housing fee"], source:"Newfoundland and Labrador — Service Animal Act and Regulations", url:"https://www.assembly.nl.ca/Legislation/sr/regulations/rc220052.htm", complaint:"Contact the Newfoundland and Labrador Human Rights Commission.", complaintUrl:"https://thinkhumanrights.ca/complaints/" },
  NS: { access:"Nova Scotia's Service Dogs Act gives public-access and tenancy protection to provincially certified teams. Certification is voluntary; an uncertified team may seek accommodation under the Human Rights Act.", accessBullets:["A certified handler must carry and produce the team's identification card on request.","Do not apply U.S. ADA rules or the U.S. two-question test in Nova Scotia."], training:"Dog-in-training certification is available only through an authorized representative of an accredited service-dog training school training on that school's behalf.", trainingBullets:["A certified dog-in-training team receives the Act's applicable protection.","The category does not automatically cover every independent owner-trainer."], questions:["For access claimed under the Service Dogs Act, a place may ask for the Nova Scotia identification card."], prohibited:["Deny a certified team access protected by the Service Dogs Act","Treat lack of certification as an automatic answer to a Human Rights Act accommodation request"], source:"Nova Scotia — Service Dogs Act and Regulations", url:"https://novascotia.ca/servicedogs/", complaint:"Use the Nova Scotia Service Dog Program or Human Rights Commission route appropriate to the issue.", complaintUrl:"https://novascotia.ca/servicedogs/" },
  ON: { access:"Ontario requires accessible customer service for a person accompanied by a guide dog or service animal in public-facing areas unless another law excludes it.", accessBullets:["The animal qualifies through readily identifiable visual indicators or authorized health-professional documentation.","Ontario does not require one government service-animal certificate or ID card."], training:"Ontario does not grant blanket province-wide public access to every service animal in training.", trainingBullets:["Voluntary organizational policies are different from a guaranteed statutory right.","Human Rights Code accommodation remains fact-specific."], questions:["If the animal is not readily identifiable, a provider may ask for documentation from an authorized regulated health professional."], prohibited:["Require a specific certificate where status is otherwise established","Charge a pet fee for a qualifying service animal"], source:"Government of Ontario — Accessibility and service animals", url:"https://www.ontario.ca/page/accessibility-ontario-what-you-need-to-know", complaint:"Use the Human Rights Tribunal of Ontario process for discrimination.", complaintUrl:"https://tribunalsontario.ca/hrto/" },
  PE: { access:"Prince Edward Island treats service-animal access as disability accommodation under the Human Rights Act.", accessBullets:["The animal must relate to a disability need and remain controlled.","Parks Canada rules for PEI National Park must not be generalized to every provincial business."], training:"No official PEI province-wide rule has been verified granting every service animal in training automatic public access.", trainingBullets:["Parks Canada welcomes animals in training at PEI National Park, but that is a federal-site policy.","Seek permission unless the animal already qualifies as the handler's service animal."], questions:["A provider may seek reasonable information needed to assess disability accommodation when it is not apparent."], prohibited:["Refuse disability accommodation based only on a general no-pets rule"], source:"PEI Human Rights Commission — Service Animals", url:"https://www.peihumanrights.ca/sites/www.peihumanrights.ca/files/Service%20Animals%20Apr%202023_0.pdf", complaint:"Contact the PEI Human Rights Commission.", complaintUrl:"https://www.peihumanrights.ca/complaints" },
  QC: { access:"Quebec's Charter protects people using a guide or assistance dog to alleviate a disability in services, transport, work, recreation and housing.", accessBullets:["Quebec has no government service-dog certification or official registry.","A training-organization marker and proof of specialized training may be relevant.","Accommodation may be limited only where undue hardship is established."], training:"Official Quebec guidance does not create automatic public access for every dog that is only in training.", trainingBullets:["A trainer without a disability-related accommodation should obtain permission unless another specific rule applies."], questions:["A provider may seek reasonable proof of specialized assistance training when the role is not otherwise established."], prohibited:["Routine demands for a diagnosis or full medical file","Charge an additional fee because of a guide or assistance dog"], source:"Quebec CDPDJ — Guide and assistance animals", url:"https://www.cdpdj.qc.ca/en/your-obligations/prohibited-grounds/handicap-animaux", complaint:"Contact the Commission des droits de la personne et des droits de la jeunesse.", complaintUrl:"https://www.cdpdj.qc.ca/en/file-a-complaint" },
  SK: { access:"Saskatchewan's Human Rights Code protects disability accommodation involving service animals in public services, housing, employment and education.", accessBullets:["There is no official Saskatchewan government registry or universally required ID.","Reasonable documentation may be requested when need is not obvious."], training:"The Saskatchewan Human Rights Commission says animals in training are typically afforded the same access as trained service animals when under control.", trainingBullets:["Training access remains subject to control, behaviour and individualized health-and-safety concerns."], questions:["If the role is not obvious, a provider may ask whether the animal is disability-required and what work or task it is trained to perform."], prohibited:["Demand an official government certificate or registry entry Saskatchewan does not issue","Ask for a diagnosis when it is not needed for accommodation"], source:"Saskatchewan Human Rights Commission — Service animals FAQ", url:"https://saskhrc.ca/education-resources/service-animals-support-animals-questions-answers-for-businesses-and-service-providers/", complaint:"Contact the Saskatchewan Human Rights Commission.", complaintUrl:"https://saskhrc.ca/filing-a-complaint/" },
};

for (const [code,name,authority,url] of [["NT","Northwest Territories","Northwest Territories Human Rights Commission","https://nwthumanrights.ca/"],["NU","Nunavut","Nunavut Human Rights Tribunal","https://nhrt.ca/"],["YT","Yukon","Yukon Human Rights Commission","https://yukonhumanrights.ca/"]] as const) ENTRIES[code] = { status:"partial", access:`${name} requires disability accommodation in covered services. PawPass has not found sufficiently specific official guidance to state a universal ID, inquiry or service-animal rule.`, accessBullets:["PawPass does not import U.S. ADA rules or another province's rules into this territory.","Use the official human-rights authority for an individualized answer."], training:`No verified territory-wide service-animal-in-training access rule is currently published in PawPass for ${name}.`, trainingBullets:["Obtain permission unless the animal already qualifies as a disability accommodation."], prohibited:["Refuse to consider disability accommodation solely because an animal is involved"], source:authority, url, complaint:`Contact the ${authority}.`, complaintUrl:url };

export function bundledCanadianRules(state?: string): EffectiveRules | null {
  if (!state || !ENTRIES[state]) return null;
  const item = ENTRIES[state];
  const citation = { ref:item.source, url:item.url };
  return {
    jurisdiction:{country:"CA",state,county:null,city:null},
    allowedQuestions:(item.questions ?? []).map((question,index)=>({id:`${state}-q${index+1}`,question})),
    prohibitedActions:(item.prohibited ?? []).map((action,index)=>({id:`${state}-p${index+1}`,action,citation:item.source})),
    citations:[citation,{ref:"Canadian Transportation Agency — Service dogs guide",url:"https://otc-cta.gc.ca/eng/publication/service-dogs-a-guide"}],
    notes:[`Province or territory summary reviewed ${CANADA_RIGHTS_REVIEWED_AT.slice(0,10)}.`],
    layers:["FEDERAL","STATE"],
    jurisdictionReviewStatus:item.status ?? "verified",
    jurisdictionReviewedAt:CANADA_RIGHTS_REVIEWED_AT.slice(0,10),
    escalationGuidance:[{id:`${state}-complaint`,step:item.complaint,url:item.complaintUrl}],
    rightsSections:[
      {id:"public_access",title:"Public places",summary:item.access,bullets:item.accessBullets,citations:[citation],status:item.status === "partial" ? "baseline" : "verified"},
      {id:"in_training",title:"Service animals in training",summary:item.training,bullets:item.trainingBullets,citations:[citation],status:item.status === "partial" ? "baseline" : "verified"},
      {id:"air_travel",title:"Federally regulated transportation",summary:"Canadian federal transportation accessibility rules apply to airlines and other federally regulated carriers. Documentation and advance-notice requirements may differ from ordinary public access.",bullets:[],citations:[{ref:"Canadian Transportation Agency — Service dogs guide",url:"https://otc-cta.gc.ca/eng/publication/service-dogs-a-guide"}],status:"verified"},
    ],
  };
}
