import type { EffectiveRules } from "./api";

export const UK_RIGHTS_REVIEWED_AT="2026-08-05T00:00:00.000Z";

const ehcr={ref:"EHRC — Assistance dogs guide for businesses",url:"https://www.equalityhumanrights.com/guidance/assistance-dogs-guide-businesses-and-service-providers"};
const equalityAct={ref:"Equality Act 2010",url:"https://www.legislation.gov.uk/ukpga/2010/15/contents"};

function greatBritain(state:string,nation:string):EffectiveRules {
  const training="There is no blanket UK statutory public-access right for every assistance dog in training. The Equality Act protects the disabled person's reasonable-adjustment rights, not an automatic trainer-only category.";
  return {
    jurisdiction:{country:"GB",state,county:null,city:null},layers:["FEDERAL","STATE"],jurisdictionReviewStatus:"verified",jurisdictionReviewedAt:"2026-08-05",
    allowedQuestions:[{id:"gb-q1",question:"A provider may ask limited, respectful questions needed to understand the disability-related adjustment, but should not demand a diagnosis or insist on one branded ID scheme."}],
    prohibitedActions:[{id:"gb-p1",action:"Apply a no-dogs policy without considering a reasonable adjustment",citation:"Equality Act 2010"},{id:"gb-p2",action:"Provide worse service or charge extra because a disabled customer uses an assistance dog",citation:"Equality Act 2010"},{id:"gb-p3",action:"Treat membership in one assistance-dog organisation as the only valid proof",citation:"EHRC guidance"}],
    citations:[ehcr,equalityAct],notes:["UK nation summary reviewed 2026-08-05."],escalationGuidance:[{id:"gb-complaint",step:"Contact the Equality Advisory and Support Service for advice about possible discrimination.",url:"https://www.equalityadvisoryservice.com/"}],
    rightsSections:[
      {id:"public_access",title:"Services and public places",summary:`In ${nation}, the Equality Act 2010 requires service providers to avoid disability discrimination and make reasonable adjustments. This commonly requires changing a no-dogs policy for a disabled assistance-dog user.`,bullets:["The duty is owed to the disabled person and is not limited to dogs trained by a particular charity.","There is no universal government assistance-dog register, certificate or ID card.","Emotional-support animals are not separately defined, but individual circumstances may still require a reasonable-adjustment assessment.","Allergies or fear do not automatically justify a blanket ban."],citations:[ehcr,equalityAct],status:"verified"},
      {id:"in_training",title:"Assistance dogs in training",summary:training,bullets:["A disabled owner-trainer may have an individual reasonable-adjustment claim.","A trainer not relying on their own disability rights should seek permission unless a setting-specific rule applies.","Taxi guidance encourages voluntary acceptance of trainee dogs but does not describe it as the statutory carriage duty."],citations:[ehcr,equalityAct],status:"verified"},
      {id:"housing",title:"Housing",summary:"Housing and premises involve separate legal provisions and an individualized disability-accommodation analysis.",bullets:[],citations:[equalityAct],status:"baseline"},
      {id:"employment",title:"Workplace",summary:"Workplace use is considered through the employer's reasonable-adjustment duty and individual facts.",bullets:[],citations:[equalityAct],status:"verified"},
      {id:"air_travel",title:"Transport and travel",summary:"Non-exempt taxi and private-hire drivers have statutory assistance-dog duties. Air, rail, sea and international animal-entry requirements are separate.",bullets:["Check carrier advance-notice, documentation and entry requirements."],citations:[{ref:"GOV.UK — Disabled passenger transport rights",url:"https://www.gov.uk/guidance/rights-of-disabled-passengers-on-transport"}],status:"verified"},
    ],
  };
}

export function bundledUkRules(state?:string):EffectiveRules|null {
  if(state==="ENG") return greatBritain(state,"England");
  if(state==="SCT") return greatBritain(state,"Scotland");
  if(state==="WLS") return greatBritain(state,"Wales");
  if(state!=="NIR") return null;
  const source={ref:"Equality Commission for Northern Ireland — Disability access",url:"https://www.equalityni.org/Employers-Service-Providers/Service-providers/Disability-access"};
  return {jurisdiction:{country:"GB",state,county:null,city:null},layers:["FEDERAL","STATE"],jurisdictionReviewStatus:"verified",jurisdictionReviewedAt:"2026-08-05",allowedQuestions:[{id:"nir-q1",question:"A provider may ask limited questions needed to understand a requested reasonable adjustment, without unnecessary diagnostic demands."}],prohibitedActions:[{id:"nir-p1",action:"Refuse or lower service because of disability without lawful justification",citation:"Disability Discrimination Act 1995"},{id:"nir-p2",action:"Fail to consider a reasonable adjustment to a no-dogs policy",citation:"ECNI guidance"}],citations:[source],notes:["Northern Ireland summary reviewed 2026-08-05."],escalationGuidance:[{id:"nir-complaint",step:"Contact the Equality Commission for Northern Ireland for advice.",url:"https://www.equalityni.org/ContactUs"}],rightsSections:[{id:"public_access",title:"Services and public places",summary:"Northern Ireland uses the Disability Discrimination Act 1995 framework, not the Equality Act 2010 framework used in Great Britain. Service providers must avoid disability discrimination and consider reasonable adjustments.",bullets:["A no-dogs policy may need adjustment for a disabled assistance-dog user.","There is no universal government assistance-dog register or ID card.","Use Northern Ireland guidance, not U.S. ADA or Great Britain-only wording."],citations:[source],status:"verified"},{id:"in_training",title:"Assistance dogs in training",summary:"No blanket Northern Ireland statutory access right has been identified for every assistance dog in training.",bullets:["A disabled owner-trainer's reasonable-adjustment rights are fact-specific.","Other trainers should seek permission unless a setting-specific rule applies."],citations:[source],status:"verified"},{id:"housing",title:"Housing",summary:"Housing requires a separate, individualized disability-accommodation analysis.",bullets:[],citations:[source],status:"baseline"},{id:"employment",title:"Workplace",summary:"Workplace use is considered through Northern Ireland's disability reasonable-adjustment duties.",bullets:[],citations:[source],status:"verified"},{id:"air_travel",title:"Transport and travel",summary:"Transport can involve separate Northern Ireland, UK-wide and carrier rules. Check the operator and official travel guidance.",bullets:[],citations:[source],status:"baseline"}]};
}
