export type SditScope = "broad" | "restricted" | "none";
export type SditLaw = { citation:string; scope:SditScope; trainer:string; conditions?:string; officialUrl?:string };

const MSU = "https://www.animallaw.info/content/service-animal-trainer-access-laws";

export const US_SDIT_LAWS: Record<string,SditLaw> = {
  AL:{citation:"Ala. Code §§ 21-7-4, 3-1-7",scope:"broad",trainer:"A service-animal trainer while engaged in training; a separate guide-dog provision is limited to accredited-school employees."},
  AK:{citation:"Alaska Stat. § 11.76.133",scope:"restricted",trainer:"A person authorized under a school, agency, or training-facility program.",conditions:"The animal must be identified as in training."},
  AZ:{citation:"Ariz. Rev. Stat. § 11-1024",scope:"broad",trainer:"Any trainer or individual with a disability training a service animal."},
  AR:{citation:"Ark. Code § 20-14-308",scope:"restricted",trainer:"A dog trainer training a guide, signal, or service dog.",conditions:"The statute's wording is tied to visual, hearing, or other physical disabilities."},
  CA:{citation:"Cal. Civ. Code § 54.2",scope:"restricted",trainer:"Authorized guide-, signal-, or service-dog trainers.",conditions:"Leash and an authorized county or animal-control identification tag are required."},
  CO:{citation:"Colo. Rev. Stat. § 24-34-803",scope:"broad",trainer:"A service-animal trainer or a disabled individual training an animal as that person's service animal.",conditions:"Covers employment, housing, public accommodations, public programs, transportation, and other places open to the public.",officialUrl:"https://content.leg.colorado.gov/sites/default/files/images/olls/2014a_sl_250.pdf"},
  CT:{citation:"Conn. Gen. Stat. § 46a-64",scope:"restricted",trainer:"A person training a guide dog or a dog assisting a deaf or mobility-impaired person."},
  DE:{citation:"6 Del. C. § 4504",scope:"broad",trainer:"An individual training a service animal for a person with a disability."},
  FL:{citation:"Fla. Stat. § 413.08",scope:"broad",trainer:"Any trainer while engaged in training a service animal.",officialUrl:"https://www.flsenate.gov/Laws/Statutes/2025/413.08"},
  GA:{citation:"Ga. Code § 30-4-2",scope:"restricted",trainer:"An agent or employee of a seeing-eye, hearing, service-, or guide-dog school.",conditions:"The trainer must be identified as the school's agent or employee."},
  HI:{citation:"No statewide trainer-access statute identified",scope:"none",trainer:"No statewide public-access protection for service animals in training was identified."},
  ID:{citation:"Idaho Code § 56-704B",scope:"restricted",trainer:"A disabled individual training or socializing a future service dog; other trainers tied to a recognized school or disability-serving organization.",conditions:"Non-disabled trainers must carry program identification and the dog must be visibly identified as in training."},
  IL:{citation:"775 ILCS 30/3",scope:"broad",trainer:"A trainer of support, guide, seizure-alert, seizure-response, or hearing dogs."},
  IN:{citation:"Ind. Code § 16-32-3-2",scope:"broad",trainer:"A service-animal trainer engaged in the training process."},
  IA:{citation:"Iowa Code § 216C.11",scope:"broad",trainer:"A disabled person, assisting person, or person training a service animal.",conditions:"The animal must be under control; the handler is liable for damage."},
  KS:{citation:"Kan. Stat. § 39-1109",scope:"restricted",trainer:"A professional trainer from a recognized training center."},
  KY:{citation:"Ky. Rev. Stat. § 258.500",scope:"restricted",trainer:"An assistance-dog trainer.",conditions:"Trainer identification must be carried."},
  LA:{citation:"La. Rev. Stat. §§ 46:1952, 46:1955",scope:"broad",trainer:"Any trainer or puppy raiser during service-dog training."},
  ME:{citation:"17 Me. Rev. Stat. § 1312",scope:"broad",trainer:"An especially trained service-dog trainer engaged in actual training."},
  MD:{citation:"Md. Human Services § 7-704",scope:"broad",trainer:"A professional or volunteer who trains or raises service animals."},
  MA:{citation:"Mass. Gen. Laws ch. 129, §§ 39D, 39F",scope:"broad",trainer:"A person raising or training a service dog, including hearing, guide, or assistance dogs."},
  MI:{citation:"Mich. Comp. Laws § 750.502c",scope:"broad",trainer:"An animal raiser or trainer accompanied for training or socialization."},
  MN:{citation:"Minn. Stat. § 363A.19",scope:"broad",trainer:"A person training a dog to be a service dog.",conditions:"The trainer is liable for damage."},
  MS:{citation:"Miss. Code §§ 43-6-153, 43-6-155",scope:"restricted",trainer:"A professional trainer or volunteer serving with a professional trainer."},
  MO:{citation:"Mo. Rev. Stat. § 209.152",scope:"restricted",trainer:"A trainer from a recognized training center or a member of a statutory service-dog team."},
  MT:{citation:"Mont. Code § 49-4-214",scope:"restricted",trainer:"A person with a disability accompanied by a service animal in training.",conditions:"Visible written identification on a leash, collar, cape, harness, or backpack must be legible from 20 feet."},
  NE:{citation:"Neb. Rev. Stat. § 20-127",scope:"broad",trainer:"A bona fide trainer of a service animal."},
  NV:{citation:"Nev. Rev. Stat. § 651.075",scope:"broad",trainer:"A person or employee training a service animal."},
  NH:{citation:"N.H. Rev. Stat. § 167-D:6",scope:"broad",trainer:"A service-animal trainer engaged in the actual training process."},
  NJ:{citation:"N.J. Stat. § 10:5-29.3",scope:"broad",trainer:"A service- or guide-dog trainer engaged in actual training."},
  NM:{citation:"N.M. Stat. §§ 28-11-2, 28-11-3",scope:"restricted",trainer:"An owner, trainer, or handler controlling a qualified service animal being trained for a disabled individual."},
  NY:{citation:"N.Y. Civil Rights Law § 47-b",scope:"restricted",trainer:"A person qualified to train a guide, hearing, or service dog."},
  NC:{citation:"N.C. Gen. Stat. § 168-4.2",scope:"broad",trainer:"A person training an animal to become a service animal.",conditions:"A collar and leash, harness, or cape must identify the animal as in training.",officialUrl:"https://www.ncleg.gov/enactedlegislation/statutes/html/bysection/chapter_168/gs_168-4.2.html"},
  ND:{citation:"N.D. Cent. Code § 25-13-02.1",scope:"restricted",trainer:"A trainer associated with a nationally recognized service-animal training program.",conditions:"Notify an onsite manager and wear the program's photo identification card."},
  OH:{citation:"Ohio Rev. Code § 955.43",scope:"restricted",trainer:"A trainer of an assistance dog under the statute's guide, hearing, or mobility framework."},
  OK:{citation:"Okla. Stat. tit. 7, § 19.1",scope:"restricted",trainer:"A dog trainer from a recognized training center."},
  OR:{citation:"Or. Rev. Stat. § 659A.143",scope:"broad",trainer:"An assistance-animal trainer accompanied by an assistance-animal trainee."},
  PA:{citation:"18 Pa. Cons. Stat. § 7325",scope:"broad",trainer:"A person training a service, guide, support dog, or other aid animal for a disabled individual."},
  RI:{citation:"R.I. Gen. Laws § 40-9.1-2.1",scope:"broad",trainer:"Every trainer or puppy raiser of a service animal."},
  SC:{citation:"S.C. Code § 43-33-20",scope:"broad",trainer:"A trainer engaged in training an assistance or guide dog."},
  SD:{citation:"S.D. Codified Laws § 20-13-23.2",scope:"broad",trainer:"A service-animal trainer.",conditions:"The animal must wear a collar and leash, harness, or cape identifying it as in training."},
  TN:{citation:"Tenn. Code § 62-7-112",scope:"restricted",trainer:"An accredited-school dog-guide trainer.",conditions:"School credentials and prescribed harness/leash control are required."},
  TX:{citation:"Tex. Human Resources Code § 121.003",scope:"restricted",trainer:"An approved trainer accompanied by a service animal in training."},
  UT:{citation:"Utah Code § 26B-6-803",scope:"broad",trainer:"An individual accompanied by an animal being trained as a service animal."},
  VT:{citation:"9 V.S.A. § 4502",scope:"broad",trainer:"An individual training an animal to perform as a service animal for a disabled individual."},
  VA:{citation:"Va. Code § 51.5-44",scope:"restricted",trainer:"Experienced trainers, recognized-organization trainers, continuing trainers, or members of a statutory three-unit team.",conditions:"The dog must be at least six months old and use the identification equipment specified for the training category."},
  WA:{citation:"Wash. Rev. Code § 49.60.215",scope:"broad",trainer:"A service-animal trainer accompanied by a trainee.",conditions:"The trainee must be housebroken and under control by tether or other effective means."},
  WV:{citation:"W. Va. Code § 5-15-4",scope:"restricted",trainer:"A person certified as a service-animal trainer while engaged in training."},
  WI:{citation:"Wis. Stat. § 106.52",scope:"restricted",trainer:"A service-animal trainer.",conditions:"The animal must wear a harness or leash and special cape."},
  WY:{citation:"Wyo. Stat. § 35-13-205",scope:"broad",trainer:"A person accompanied by a dog being trained to perform disability-related work or tasks."},
  DC:{citation:"D.C. Code § 7-1002",scope:"broad",trainer:"A service-animal trainer or owner training an animal as a service animal.",officialUrl:"https://code.dccouncil.gov/us/dc/council/code/sections/7-1002"},
};

export function sditSourceUrl(law:SditLaw) { return law.officialUrl ?? MSU; }
